import { motion } from "framer-motion"
import { Card, CardHeader } from "../ui/Card"
import { Star } from "lucide-react"

const testimonials = [
    {
        name: "Dr. Sarah Johnson",
        role: "Professor of Computer Science",
        content: "TAP has completely revolutionized how I prepare for my classes. The automated note generation is a game-changer.",
        rating: 5,
    },
    {
        name: "Mark Thompson",
        role: "High School History Teacher",
        content: "My students love the flashcards generated by TAP. It's helped improve their test scores significantly.",
        rating: 5,
    },
    {
        name: "Emily Chen",
        role: "University Lecturer",
        content: "The assignment generator saves me hours every week. I can focus more on teaching and less on administrative tasks.",
        rating: 5,
    },
]

export function Testimonials() {
    return (
        <section className="py-24 bg-black/20 relative">
            <div className="container mx-auto px-6">
                <div className="text-center mb-16">
                    <motion.h2
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-3xl md:text-5xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-white to-white/60"
                    >
                        Loved by Educators Worldwide
                    </motion.h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {testimonials.map((testimonial, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: index * 0.1 }}
                        >
                            <Card className="h-full border-white/5 bg-white/5 backdrop-blur-sm">
                                <CardHeader>
                                    <div className="flex gap-1 mb-4">
                                        {[...Array(testimonial.rating)].map((_, i) => (
                                            <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                                        ))}
                                    </div>
                                    <p className="text-lg italic text-white/80 mb-6">"{testimonial.content}"</p>
                                    <div>
                                        <p className="font-semibold text-white">{testimonial.name}</p>
                                        <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                                    </div>
                                </CardHeader>
                            </Card>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    )
}
